image: docker:latest

services:
  - docker:dind

.build_push:
  only:
    changes:
      - .gitlab-ci.yml
      - ${CI_JOB_NAME}/.gitlab-ci.yml
      - ${CI_JOB_NAME}/Dockerfile
      - ${CI_JOB_NAME}/dotfiles/**/*
  script:
    - docker login -u gitlab-ci-token -p ${CI_BUILD_TOKEN} ${CI_REGISTRY}
    - docker build --pull -t ${CI_REGISTRY_IMAGE}/${CI_JOB_NAME}:latest ./${CI_JOB_NAME}
    - docker build --pull -t ${CI_REGISTRY_IMAGE}/${CI_JOB_NAME}:${SHORT_TAG} ./${CI_JOB_NAME}
    - docker build --pull -t ${CI_REGISTRY_IMAGE}/${CI_JOB_NAME}:${LONG_TAG} ./${CI_JOB_NAME}
    - docker push ${CI_REGISTRY_IMAGE}/${CI_JOB_NAME}:latest
    - docker push ${CI_REGISTRY_IMAGE}/${CI_JOB_NAME}:${SHORT_TAG}
    - docker push ${CI_REGISTRY_IMAGE}/${CI_JOB_NAME}:${LONG_TAG}

stages:
  - alpine
  - alpine-dev
  - alpine-dotnet
  - alpine-dotnet-sdk

include:
  - local: "/alpine/.gitlab-ci.yml"
  - local: "/alpine-dev/.gitlab-ci.yml"
  - local: "/alpine-dotnet/.gitlab-ci.yml"
  - local: "/alpine-dotnet-sdk/.gitlab-ci.yml"
