image: docker:latest

services:
  - docker:dind

before_script:
  - docker login -u gitlab-ci-token -p ${CI_BUILD_TOKEN} ${CI_REGISTRY}

base-alpine:
  stage: build
  script:
    - docker build --pull -t ${CI_REGISTRY_IMAGE}/base-alpine:latest ./base-alpine
    - docker push ${CI_REGISTRY_IMAGE}/base-alpine:latest

base-alpine-tag:
  stage: build
  only:
    - tags
  script:
    - docker build --pull -t ${CI_REGISTRY_IMAGE}/base-alpine:${CI_COMMIT_TAG} ./base-alpine
    - docker push ${CI_REGISTRY_IMAGE}/base-alpine:${CI_COMMIT_TAG}
  dependencies:
    - base-alpine

base-sdk-alpine:
  stage: build
  script:
    - docker build --pull -t ${CI_REGISTRY_IMAGE}/base-sdk-alpine:latest ./base-sdk-alpine
    - docker push ${CI_REGISTRY_IMAGE}/base-sdk-alpine:latest
  dependencies:
    - base-alpine

base-sdk-alpine-tag:
  stage: build
  only:
    - tags
  script:
    - docker build --pull -t ${CI_REGISTRY_IMAGE}/base-sdk-alpine:${CI_COMMIT_TAG} ./base-sdk-alpine
    - docker push ${CI_REGISTRY_IMAGE}/base-sdk-alpine:${CI_COMMIT_TAG}
  dependencies:
    - base-sdk-alpine

netcore-alpine:
  stage: build
  script:
    - docker build --pull -t ${CI_REGISTRY_IMAGE}/netcore-alpine:latest ./netcore-alpine
    - docker push ${CI_REGISTRY_IMAGE}/netcore-alpine:latest
  dependencies:
    - base-alpine

netcore-alpine-tag:
  stage: build
  only:
    - tags
  script:
    - docker build --pull -t ${CI_REGISTRY_IMAGE}/netcore-alpine:${CI_COMMIT_TAG} ./netcore-alpine
    - docker push ${CI_REGISTRY_IMAGE}/netcore-alpine:${CI_COMMIT_TAG}
  dependencies:
    - netcore-alpine

netcore-sdk-alpine:
  stage: build
  script:
    - docker build --pull -t ${CI_REGISTRY_IMAGE}/netcore-sdk-alpine:latest ./netcore-sdk-alpine
    - docker push ${CI_REGISTRY_IMAGE}/netcore-sdk-alpine:latest
  dependencies:
    - base-sdk-alpine

netcore-sdk-alpine-tag:
  stage: build
  only:
    - tags
  script:
    - docker build --pull -t ${CI_REGISTRY_IMAGE}/netcore-sdk-alpine:${CI_COMMIT_TAG} ./netcore-sdk-alpine
    - docker push ${CI_REGISTRY_IMAGE}/netcore-sdk-alpine:${CI_COMMIT_TAG}
  dependencies:
    - netcore-sdk-alpine
