image: docker:latest

services:
  - docker:dind

variables:
  ALPINE_SHORT_VERSION: "3.10"
  ALPINE_LONG_VERSION: "3.10.1"
  DOTNET_VERSION: "2.2"
  DOTNET_RUNTIME_VERSION: "2.2.6"
  DOTNET_SDK_VERSION: "2.2.401"

stages:
  - alpine
  - alpine-dev
  - alpine-dotnet
  - alpine-dotnet-sdk

before_script:
  - docker login -u gitlab-ci-token -p ${CI_BUILD_TOKEN} ${CI_REGISTRY}

alpine:
  stage: alpine
  only:
    changes:
      - alpine/**/*
      - .gitlab-ci.yml
  script:
    - docker build --pull -t ${CI_REGISTRY_IMAGE}/alpine:latest ./alpine
    - docker push ${CI_REGISTRY_IMAGE}/alpine:latest
    - docker build --pull -t ${CI_REGISTRY_IMAGE}/alpine:${ALPINE_SHORT_VERSION} ./alpine
    - docker push ${CI_REGISTRY_IMAGE}/alpine:${ALPINE_SHORT_VERSION}
    - docker build --pull -t ${CI_REGISTRY_IMAGE}/alpine:${ALPINE_LONG_VERSION} ./alpine
    - docker push ${CI_REGISTRY_IMAGE}/alpine:${ALPINE_LONG_VERSION}
    - docker build --pull -t ${CI_REGISTRY_IMAGE}/alpine:${CI_COMMIT_REF_SLUG} ./alpine
    - docker push ${CI_REGISTRY_IMAGE}/alpine:${CI_COMMIT_REF_SLUG}

alpine-dev:
  stage: alpine-dev
  only:
    changes:
      - alpine-dev/**/*
      - .gitlab-ci.yml
  script:
    - docker build --pull -t ${CI_REGISTRY_IMAGE}/alpine-dev:latest ./alpine-dev
    - docker push ${CI_REGISTRY_IMAGE}/alpine-dev:latest
    - docker build --pull -t ${CI_REGISTRY_IMAGE}/alpine-dev:${ALPINE_SHORT_VERSION} ./alpine-dev
    - docker push ${CI_REGISTRY_IMAGE}/alpine-dev:${ALPINE_SHORT_VERSION}
    - docker build --pull -t ${CI_REGISTRY_IMAGE}/alpine-dev:${ALPINE_LONG_VERSION} ./alpine-dev
    - docker push ${CI_REGISTRY_IMAGE}/alpine-dev:${ALPINE_LONG_VERSION}

alpine-dotnet:
  stage: alpine-dotnet
  only:
    changes:
      - alpine-dotnet/**/*
      - .gitlab-ci.yml
  script:
    - docker build --pull -t ${CI_REGISTRY_IMAGE}/alpine-dotnet:latest ./alpine-dotnet
    - docker push ${CI_REGISTRY_IMAGE}/alpine-dotnet:latest
    - docker build --pull -t ${CI_REGISTRY_IMAGE}/alpine-dotnet:${DOTNET_VERSION} ./alpine-dotnet
    - docker push ${CI_REGISTRY_IMAGE}/alpine-dotnet:${DOTNET_VERSION}
    - docker build --pull -t ${CI_REGISTRY_IMAGE}/alpine-dotnet:${DOTNET_RUNTIME_VERSION} ./alpine-dotnet
    - docker push ${CI_REGISTRY_IMAGE}/alpine-dotnet:${DOTNET_RUNTIME_VERSION}

alpine-dotnet-sdk:
  stage: alpine-dotnet-sdk
  only:
    changes:
      - alpine-dotnet-sdk/**/*
      - .gitlab-ci.yml
  script:
    - docker build --pull -t ${CI_REGISTRY_IMAGE}/alpine-dotnet-sdk:latest ./alpine-dotnet-sdk
    - docker push ${CI_REGISTRY_IMAGE}/alpine-dotnet-sdk:latest
    - docker build --pull -t ${CI_REGISTRY_IMAGE}/alpine-dotnet-sdk:${DOTNET_VERSION} ./alpine-dotnet-sdk
    - docker push ${CI_REGISTRY_IMAGE}/alpine-dotnet-sdk:${DOTNET_VERSION}
    - docker build --pull -t ${CI_REGISTRY_IMAGE}/alpine-dotnet-sdk:${DOTNET_SDK_VERSION} ./alpine-dotnet-sdk
    - docker push ${CI_REGISTRY_IMAGE}/alpine-dotnet-sdk:${DOTNET_SDK_VERSION}
